version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site-data/results/:/site-data/results/:ro  # downloads
      - ./frontend/www/:/var/www/:ro  # site root
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ./frontend/ 
    depends_on:
      - backend
    environment:
      - FLASK_DEBUG=1  # FIXME: DELME
    volumes:
      - ./site-data/uploads/:/site-data/uploads/:rw 

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis
      - FLASK_DEBUG=1  # FIXME: DELME
    volumes:
      - ./model.pt:/app/model.pt:ro
      - ./site-data/uploads/:/site-data/uploads/:ro
      - ./site-data/results/:/site-data/results/:rw

  redis:
    image: redis:6-alpine
    volumes:
      - ./site-data/redis/:/data/

  dashboard:
    image: mher/flower
    command: ["celery", "flower", "--port=8001"]  
    ports:  
      - 8001:8001  
    environment:
      - CELERY_BROKER_URL=redis://redis

  